--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TizFact/HelpfulPlugin
build-by-default: true
branches:
- main
projects: [https://github.com/TizFact/HelpfulPlugin/releases/download/Minecraft/HelpfulHand.zip]
...
